# Generated by Django 5.1.5 on 2025-01-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("strain", models.CharField(max_length=255)),
                ("thc", models.CharField(max_length=50)),
                ("cbd", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("lab", models.CharField(max_length=255)),
                ("pdf", models.FileField(upload_to="lab_results/")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("thc", models.FloatField()),
                ("cbd", models.FloatField()),
                ("image", models.ImageField(upload_to="products/")),
                ("description", models.TextField()),
                ("effects", models.JSONField()),
                ("terpenes", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="retailers/")),
                ("logo_alt", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "products",
                    models.ManyToManyField(related_name="retailers", to="api.product"),
                ),
            ],
        ),
    ]
