# Generated by Django 5.1.5 on 2025-01-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homecarouselitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homecarouselitem",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("flower", "Flower"),
                    ("preroll", "Preroll"),
                    ("concentrates", "Concentrates"),
                    ("edibles", "Edibles"),
                    ("vapes", "Vapes"),
                ],
                max_length=20,
            ),
        ),
    ]
