# Generated by Django 5.1.5 on 2025-01-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="logo",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="products",
            field=models.ManyToManyField(to="api.product"),
        ),
    ]
