# Generated by Django 5.1.5 on 2025-01-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecarouselitem",
            name="display_on_frontend",
            field=models.BooleanField(default=False),
        ),
    ]
