# Generated by Django 5.1.5 on 2025-01-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homefeature",
            name="icon",
        ),
        migrations.AddField(
            model_name="homefeature",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="home-features"),
        ),
    ]
