# Generated by Django 5.1.5 on 2025-01-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_homecarouselitem_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecarouselitem",
            name="link_page",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
