# Generated by Django 5.1.5 on 2025-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_retailer_logo_alter_retailer_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="logo",
            field=models.ImageField(upload_to="retailers/"),
        ),
    ]
