# Generated by Django 5.1.5 on 2025-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_effect_terpene_remove_product_effects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="logo_alt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
