# Generated by Django 5.1.5 on 2025-01-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_homecarouselitem_display_on_frontend"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homecarouselitem",
            old_name="display_on_frontend",
            new_name="make_active",
        ),
    ]
