# Generated by Django 5.1.5 on 2025-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_homecarouselitem_link_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homecarouselitem",
            name="link_page",
            field=models.CharField(
                blank=True,
                choices=[
                    ("/about", "About"),
                    ("/products", "Products"),
                    ("/retailers", "Retailers"),
                    ("/lab-results", "Lab Results"),
                    ("/cultivation", "Cultivation"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
