# Generated by Django 5.1.5 on 2025-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_retailer_address_alter_retailer_logo_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("flower", "Flower"),
                    ("edibles", "Edibles"),
                    ("vapes", "Vapes"),
                    ("concentrates", "Concentrates"),
                ],
                default="flower",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("indica", "Indica"),
                    ("sativa", "Sativa"),
                    ("hybrid", "Hybrid"),
                ],
                default="indica",
                max_length=100,
            ),
        ),
    ]
