# Generated by Django 5.1.5 on 2025-01-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_display_on_frontend_homecarouselitem_make_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="homefeature",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="labresult",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="retailer",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
    ]
