# Generated by Django 5.1.5 on 2025-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_cart_id_alter_cartitem_id_alter_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="shopitems",
            name="available_sizes",
        ),
        migrations.RemoveField(
            model_name="shopitems",
            name="size",
        ),
        migrations.AddField(
            model_name="shopitems",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),  # Temporarily allow null and non-unique
        ),
        migrations.AddField(
            model_name="shopitems",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="api.size"),
        ),
    ]
