# Generated by Django 5.1.5 on 2025-01-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_product_category_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labresult",
            name="cbd",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="thc",
            field=models.FloatField(),
        ),
    ]
