# Generated by Django 5.1.5 on 2025-05-29 19:20

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    ShopItems = apps.get_model("api", "ShopItems")
    for item in ShopItems.objects.all():
        if not item.slug:  # Only populate if slug is currently empty
            item.slug = slugify(item.name)
            # Ensure uniqueness if multiple items have the same name initially
            counter = 1
            original_slug = item.slug
            while ShopItems.objects.filter(slug=item.slug).exclude(pk=item.pk).exists():
                item.slug = f"{original_slug}-{counter}"
                counter += 1
            item.save()


def reverse_populate_slugs(apps, schema_editor):
    # Slugs will be removed when the field is removed if we were to fully reverse,
    # or we could set them to None if the field was made nullable again.
    # For this case, making them None is safest if reversing.
    ShopItems = apps.get_model("api", "ShopItems")
    ShopItems.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_size_remove_shopitems_available_sizes_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_code=reverse_populate_slugs),
        migrations.AlterField(
            model_name="shopitems",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, blank=True
            ),  # Make unique=True, blank=True allows admin to save without it initially
        ),
    ]
