# Generated by Django 5.1.5 on 2025-01-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_homecarouselitem_link_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecarouselitem",
            name="admin_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
