# Generated by Django 5.1.5 on 2025-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_homefeature_make_active_labresult_make_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labresult",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
