# Generated by Django 5.1.5 on 2025-01-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_homecarouselitem_admin_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecarouselitem",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homefeature",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="labresult",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="retailer",
            name="make_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="cbd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="thc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
