# Generated by Django 5.1.5 on 2025-05-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_populate_shopitem_slugs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Shop Categories",
            },
        ),
        migrations.AlterField(
            model_name="shopitems",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_items",
                to="api.shopcategory",
            ),
        ),
    ]
