# Generated by Django 5.1.5 on 2025-01-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_labresult_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labresult",
            name="category",
        ),
    ]
