# Generated by Django 5.1.5 on 2025-01-22 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_labresult_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homefeature",
            name="image",
            field=models.ImageField(null=True, upload_to="home-features"),
        ),
        migrations.AlterField(
            model_name="homefeature",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="homefeature",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_results",
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
